### PR TITLE
Convert to noarch

### PR DESCRIPTION
**Pull request by dbast**
There is no compiled code and there are no architecture/platform/python-version specific dependencies, which makes it possible to convert the recipe to `noarch: python` https://conda-forge.org/docs/maintainer/knowledge_base.html#noarch-builds ... so instead of 34 builds there will be then one single build that creates a package available for all platforms / python versions.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dbast** [comment]
@conda-forge-admin, please rerender

**Comment by dbast** [comment]
@conda-forge-admin, please rerender

**Review by xmnlab — APPROVED** [review]
Lgtm! Thanks for working on that.

Let's wait a bit here, maybe more people would want to review this PR

**Review by nicoddemus — APPROVED** [review]
Looks OK, but does anybody know why it is split into two outputs originally?

**Comment by xmnlab** [comment]
IIRC this package name was was originally pre_commit and we wanted to change to pre-commit and in order to keep previous user workflow working we decided to have both names

**Comment by nicoddemus** [comment]
Ahh thanks for the explanation!

**Comment by xmnlab** [comment]
@nicoddemus I was a bit wrong about that explanation XD
I just find the PR that added that: https://github.com/conda-forge/pre-commit-feedstock/pull/11
actually it seems that there was the package from a feedstock repo but using the name pre_commit .. and that repo was archived. the problem was that some people were using that and a bunch of CI that was using that was breaking.
IIRC as pypi accept both kind of names .. it was necessary to keep that name too

**Pull request merged**
