### PR TITLE
Fix virtualenv dependency

### PR DESCRIPTION
**Pull request by asottile**
Resolves pre-commit/pre-commit#1458

### CODE REVIEW

**Comment by xmnlab** [comment]
it seems the last version available for virtualenv package is 16.7.5

I will check what is happening there https://github.com/conda-forge/virtualenv-feedstock/pulls

**Comment by nicoddemus** [comment]
@conda-forge-admin, please restart ci

**Comment by nicoddemus** [comment]
@conda-forge-admin, please restart ci

**Comment by nicoddemus** [comment]
@conda-forge-admin, please restart ci

(virtualenv for py38 was merged a few hours ago)

**Comment by nicoddemus** [comment]
@marcelotrevisani meanwhile, could you mark the current `2.4.0` [packages in conda-forge](https://anaconda.org/conda-forge/pre-commit/files) as "broken"? Thanks!

**Comment by nicoddemus** [comment]
@ocefpaf might be able to help with https://github.com/conda-forge/pre-commit-feedstock/pull/20#issuecomment-630357471 as well. 👍

**Comment by ocefpaf** [comment]
> @marcelotrevisani meanwhile, could you mark the current `2.4.0` [packages in conda-forge](https://anaconda.org/conda-forge/pre-commit/files) as "broken"? Thanks!

We have a new way to mark packages as broken with users PRs:

https://conda-forge.org/docs/maintainer/updating_pkgs.html#maint-fix-broken-packages

Don't worry about this one though. I already did it.

**Comment by ocefpaf** [comment]
@conda-forge-admin, please restart ci

**Comment by nicoddemus** [comment]
Oh that's awesome, good to know, thanks!

**Comment by nicoddemus** [comment]
Hooray! 🎉

**Comment by nicoddemus** [comment]
Thanks everyone!

**Comment by marcelotrevisani** [comment]
Just saw your message now, sorry
I am glad that got it sorted! :)

**Pull request merged**
